name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update & install dependensies packeges
      uses: actions/setup-depend@v1
      with:
        apt-transport-https: latest
        ca-certificates: latest
        curl: latest
        software-properties-common: latest
#      run: |
#        sudo apt-get update && sudo apt-get install --assume-yes apt-transport-https ca-certificates \
#        curl software-properties-common
    - name: Add Docker’s official GPG key
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Install docker-ce
      run: |
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && sudo apt-get install --assume-yes docker-ce docker-ce-cli containerd.io
    - name: Run a BUILD.
      run: sudo docker build .
