name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run a BUILD.
      run: docker build -t abrakadabra21099/spice-console -t abrakadabra21099/spice-console:0 -t abrakadabra21099/spice-console:0.1 .
    - name: Push into docker hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abrakadabra21099/spice-console
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
